---

- name: Get management address details
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/shared/system/easy-setup"
    timeout: "{{ bigiq_onboard_timeout }}"
    validate_certs: "{{ bigiq_onboard_validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
  register: ez
  when: bigiq_onboard_discovery_address is not defined

- name: Set discovery address
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/shared/identified-devices/config/discovery"
    method: PUT
    timeout: "{{ bigiq_onboard_timeout }}"
    validate_certs: "{{ bigiq_onboard_validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
    body:
      discoveryAddress: "{{ ez.json.managementIpAddress[:-3] }}"
    body_format: json
  when: bigiq_onboard_discovery_address is not defined

- name: Check discovery address is correct
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/shared/identified-devices/config/discovery"
    timeout: "{{ bigiq_onboard_timeout }}"
    validate_certs: "{{ bigiq_onboard_validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
  register: result
  until: ez.json.managementIpAddress[:-3] == result.json.discoveryAddress
  retries: 5
  delay: 3
  when: bigiq_onboard_discovery_address is not defined

############ from here when Discovery IP is defined

- include_tasks: setup_network.yaml
  when: bigiq_onboard_discovery_address is defined

- name: Set discovery address to self-ip
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/shared/system/easy-setup"
    method: PATCH
    timeout: "{{ bigiq_onboard_timeout }}"
    validate_certs: "{{ bigiq_onboard_validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
    body:
      selfIpAddresses:
        - address: "{{ bigiq_onboard_discovery_address }}"
          vlan: discovery
          iface: "1.1"
    body_format: json
  when: bigiq_onboard_discovery_address is defined






