---

- name: Activate Fraud Protection service
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/cm/websafe/tasks/add-listener"
    timeout: "{{ register_cm_timeout }}"
    validate_certs: "{{ register_cm_validate_certs }}"
    method: POST
    body:
      module: websafe
      listenerInterfaceAddress: "{{ register_dcd_listener }}"
      deviceReference:
        link: "{{ device_ref }}"
    body_format: json
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
    status_code: 200,202
  register: asws
  changed_when: asws.status in [200, 202]
  until: asws.status in [200, 202] or 'Only one task can be created at a time' not in asws.json.message
  retries: 120
  delay: 2

- name: Set task ID
  set_fact:
    task_id: "{{ asws.json.id }}"

- name: Wait for Fraud Protection service activation to complete
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/cm/websafe/tasks/add-listener/{{ task_id }}"
    timeout: "{{ register_cm_timeout }}"
    validate_certs: "{{ register_cm_validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
  register: rasws1
  changed_when: rasws1.status == 200
  retries: 120
  until: rasws1.json.status in ['FINISHED', 'FAILED'] or rasws1.status == 404
  delay: 2

- name: Fail if Fraud Protection Service service activation failed
  fail:
    msg: "Fraud Protection service activation failed with: {{ rasws1 }}"
  when: rasws1.json.status == 'FAILED'
