---

- name: Activate Web Application Security service
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/cm/asm/tasks/add-syslog-listener"
    timeout: "{{ register_cm_timeout }}"
    validate_certs: "{{ register_cm_validate_certs }}"
    method: POST
    body:
      module: asm
      listenerInterfaceAddress: "{{ register_dcd_listener }}"
      deviceReference:
        link: "{{ device_ref }}"
      indexName: asmindex
    body_format: json
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
    status_code: 200,202
  register: asasm
  changed_when: asasm.status in [200, 202]
  until: asasm.status in [200, 202] or 'Only one task can be created at a time' not in asasm.json.message
  retries: 120
  delay: 2

- name: Set task ID
  set_fact:
    task_id: "{{ asasm.json.id }}"

- name: Wait for Web Application Security service activation to complete
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/cm/asm/tasks/add-syslog-listener/{{ task_id }}"
    timeout: "{{ register_cm_timeout }}"
    validate_certs: "{{ register_cm_validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
  register: asasm1
  changed_when: asasm.status == 200
  retries: 120
  until: asasm1.json.status in ['FINISHED', 'FAILED'] or asasm1.status == 404
  delay: 2

- name: Fail if Web Application Security service activation failed
  fail:
    msg: "Web Application Security service activation failed with: {{ asasm1 }}"
  when: asasm1.json.status == 'FAILED'
