---

- name: De-activate DoS Protection service
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/cm/security-shared/tasks/remove-dos-listener"
    timeout: "{{ register_cm_timeout }}"
    validate_certs: "{{ register_cm_validate_certs }}"
    method: POST
    body:
      module: dos
      deviceReference:
        link: "shared/resolver/device-groups/cm-dosevents-allLoggingNodes/devices/{{ device_id }}"
    body_format: json
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
    status_code: 200,202
  register: dsdos
  changed_when: dsdos.status in [200, 202]
  until: dsdos.status in [200, 202]
  retries: 120
  delay: 2

- name: Set task ID
  set_fact:
    task_id: "{{ dsdos.json.id }}"

- name: Wait for DoS Protection service de-activation to complete
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/cm/security-shared/tasks/remove-dos-listener/{{ task_id }}"
    timeout: "{{ register_cm_timeout }}"
    validate_certs: "{{ register_cm_validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
  register: dsdos1
  changed_when: dsdos1.status == 200
  retries: 120
  until: dsdos1.json.status in ['FINISHED', 'FAILED'] or dsdos1.status == 404
  delay: 2

- name: Fail if DoS Protection service de-activation failed
  fail:
    msg: "DoS Protection service de-activation failed with: {{ dsdos1 }}"
  when: dsdos1.json.status == 'FAILED'
