---

- name: De-activate Fraud Protection service
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/cm/websafe/tasks/remove-listener"
    timeout: "{{ register_cm_timeout }}"
    validate_certs: "{{ register_cm_validate_certs }}"
    method: POST
    body:
      module: websafe
      deviceReference:
        link: "shared/resolver/device-groups/cm-websafe-allLoggingNodes/devices/{{ device_id }}"
    body_format: json
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
    status_code: 200,202
  register: dsws
  changed_when: dsws.status in [200, 202]
  until: dsws.status in [200, 202]
  retries: 120
  delay: 2

- name: Set task ID
  set_fact:
    task_id: "{{ dsws.json.id }}"

- name: Wait for Fraud Protection service de-activation to complete
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/cm/websafe/tasks/remove-listener/{{ task_id }}"
    timeout: "{{ register_cm_timeout }}"
    validate_certs: "{{ register_cm_validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
  register: dsws1
  changed_when: dsws1.status == 200
  retries: 120
  until: dsws1.json.status in ['FINISHED', 'FAILED'] or dsws1.status == 404
  delay: 2

- name: Fail if Fraud Protection service de-activation failed
  fail:
    msg: "Fraud Protection service de-activation failed with: {{ dsws1 }}"
  when: dsws1.json.status == 'FAILED'
