---

- name: Reboot device
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/shared/failover-state"
    method: PATCH
    timeout: "{{ bigiq_onboard_timeout }}"
    validate_certs: "{{ bigiq_onboard_validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
    body:
      restart: true
    body_format: json
  listen: Restart device

- name: Wait for device to go offline
  pause:
    seconds: 30
  listen: Restart device

- name: Wait for BIG-IQ to be available
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/info/system"
    timeout: "{{ bigiq_onboard_timeout }}"
    validate_certs: "{{ bigiq_onboard_validate_certs }}"
  register: status
  until: status is success and status.json.available|bool
  retries: 60
  delay: 5
  listen: Restart device
