---

- name: Onboard all devices
  hosts: all
  roles:
    - role: f5devcentral.bigiq_onboard

- name: Remove access service
  hosts: dcd
  any_errors_fatal: true

  tasks:
    - name: Remove access service
      include_role:
        name: ansible-role-register_dcd
      vars:
        register_dcd_dcd_server: "{{ bigiq_onboard_server }}"
        register_dcd_dcd_services:
          # - access
          - afm
          - asm
          - dos
          - ipsec
          - websafe

    - name: Remove afm service
      include_role:
        name: ansible-role-register_dcd
      vars:
        register_dcd_dcd_server: "{{ bigiq_onboard_server }}"
        register_dcd_dcd_services:
          - access
          # - afm
          - asm
          - dos
          - ipsec
          - websafe

    - name: Remove asm service
      include_role:
        name: ansible-role-register_dcd
      vars:
        register_dcd_dcd_server: "{{ bigiq_onboard_server }}"
        register_dcd_dcd_services:
          - access
          - afm
          # - asm
          - dos
          - ipsec
          - websafe

    - name: Remove dos service
      include_role:
        name: ansible-role-register_dcd
      vars:
        register_dcd_dcd_server: "{{ bigiq_onboard_server }}"
        register_dcd_dcd_services:
          - access
          - afm
          - asm
          # - dos
          - ipsec
          - websafe

    - name: Remove ipsec service
      include_role:
        name: ansible-role-register_dcd
      vars:
        register_dcd_dcd_server: "{{ bigiq_onboard_server }}"
        register_dcd_dcd_services:
          - access
          - afm
          - asm
          - dos
          # - ipsec
          - websafe

    - name: Remove websafe service
      include_role:
        name: ansible-role-register_dcd
      vars:
        register_dcd_dcd_server: "{{ bigiq_onboard_server }}"
        register_dcd_dcd_services:
          - access
          - afm
          - asm
          - dos
          - ipsec
          # - websafe
