---

- name: Onboard all devices
  hosts: all
  roles:
    - role: f5devcentral.bigiq_onboard

- name: Add DCD devices to CM device serially
  hosts: cm
  tasks:
    - name: Add DCD to CM
      include_role:
        name: ansible-role-register_dcd
      vars:
        register_dcd_dcd_server: "{{ hostvars[item].bigiq_onboard_server }}"
      loop: "{{ groups['dcd'] }}"
