bigiq_onboard_server: "{{ ansible_host }}"
bigiq_onboard_hostname: bigiq-dcd-01.local
bigiq_onboard_node_type: dcd
bigiq_onboard_license_key: O1569-269458-196-7849806-1615014
### Discovery address Self-IP to set
# Use this to specify a self-ip to use as the discovery address.
# If this value is commented out (the default) it will use the
# BIG-IQ's management address as the discovery address.
#bigiq_onboard_discovery_address: 10.1.10.6/24

# The DCD server IP address to add to the CM device
register_dcd_cm_server: 10.1.1.4
# The address the DCD device should listen for events on (can be bigiq_onboard_server or bigiq_onboard_discovery_address)
register_dcd_dcd_listener: 10.1.1.6